project 'HomeBanking.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeBanking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeBanking

pod 'Stripe'
pod 'CardIO'
pod 'SVProgressHUD'

end
