<?php
DEFINE('DB_USERNAME' , 'u352797204_admin');
DEFINE('DB_PASSWORD' , 'Flow1337k.');
DEFINE('DB_HOST' , 'localhost');
DEFINE('DB_NAME' , 'u352797204_h0me');

DEFINE('USER_CREATED' , 1);
DEFINE('USER_ALREADY_CREATED' , 2);
DEFINE('USER_NOT_CREATED' , 3);
DEFINE('DATA_UPDATED' , 4);
DEFINE('DATA_NOT_UPDATED' , 5);
DEFINE('DATA_PICKED' , 6);
DEFINE('DATA_NOT_PICKED' , 7);

